### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by SpittingBull** [rolandoislas/multi-hotbar#18]
Every now and then I am getting a crash like below. I tried several times to reproduce this behaviour but it seems as if it's not trivial. I believe that breaking a lot of different blocks very quickly (like grass, flowers and the likes) had higher chances of crashing but I am not sure of course. I am using multihotbar-1.11.2-2.1.2-build-T38.jar

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at com.rolandoislas.multihotbar.HotbarLogic.reorderPickedupItem(HotbarLogic.java:408)
	at com.rolandoislas.multihotbar.HotbarLogic.playerTick(HotbarLogic.java:464)
	at com.rolandoislas.multihotbar.EventHandlerClient.playerTick(EventHandlerClient.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_383_EventHandlerClient_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:188)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by rolandoislas** [comment]
Was this on a client LAN server instance? If so, was the client hosting the server the one that crashed?

**Comment by SpittingBull** [comment]
Nope - just my local client. I am not running any server atm.

**Comment by SpittingBull** [comment]
After intensive testing I can't reproduce the behaviour with your fix multihotbar-1.11.2-2.1.3-build-T40.jar. 

Just wanted to add that I like this mod very much!
