### ISSUE TITLE
Minecraft 1.12 Server

### ISSUE THREAD

**Issue by Blobbyfish** [rolandoislas/multi-hotbar#25]
java.lang.IndexOutOfBoundsException: Index: 1704, Size: 1704
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_101]
	at java.util.ArrayList.set(Unknown Source) ~[?:1.8.0_101]
	at ayh.a(SourceFile:269) ~[minecraft_server.1.12.jar:?]
	at ayh$a.close(SourceFile:244) ~[minecraft_server.1.12.jar:?]
	at java.util.zip.DeflaterOutputStream.close(Unknown Source) ~[?:1.8.0_101]
	at java.io.FilterOutputStream.close(Unknown Source) ~[?:1.8.0_101]
	at java.io.FilterOutputStream.close(Unknown Source) ~[?:1.8.0_101]
	at ayc.b(SourceFile:160) ~[minecraft_server.1.12.jar:?]
	at ayc.a(SourceFile:145) [minecraft_server.1.12.jar:?]
	at bgv.c(SourceFile:37) [minecraft_server.1.12.jar:?]
	at bgv.run(SourceFile:30) [minecraft_server.1.12.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

The chunks are not saving and they are destroying our bases bit by bit
Anyone have a solution to how to fix?

**Comment by rolandoislas** [comment]
Multi-hotbar has no server logic. Is this crash definitely from Multi-hotbar?
