### ISSUE TITLE
Array out of bounds exception in 1.12

### ISSUE THREAD

**Issue by PrinceOfAmber** [rolandoislas/multi-hotbar#27]
Its really weird, id been playing for hours with no issue then suddenly this out of nowhere.  I was running around placing torches and blocks

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.rolandoislas.multihotbar.HotbarLogic.reorderPickedupItem(HotbarLogic.java:419)
	at com.rolandoislas.multihotbar.HotbarLogic.playerTick(HotbarLogic.java:480)
	at com.rolandoislas.multihotbar.event.EventHandlerClient.playerTick(EventHandlerClient.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_381_EventHandlerClient_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:376)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:286)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rolandoislas** [comment]
Did it crash or just log the error? If it is the latter, it is [intentionally wrapped](https://github.com/rolandoislas/multi-hotbar/blob/v1.12-3.0-beta-1/src/main/java/com/rolandoislas/multihotbar/HotbarLogic.java#L419) and can be ignored.
