### ISSUE TITLE
Player crash when another player tosses an item

### ISSUE THREAD

**Issue by mandychuu** [rolandoislas/multi-hotbar#55]
We are running a Forge modded server with a texture pack. Whenever a player tosses any item at another player, the player picking up that item immediately crashes. The server doesn't crash and the player tossing the item doesn't crash either.

I use MultiMC to run Minecraft since I play on a few different servers, but I checked my crash reports in my instances folder and didn't find one for today. My most recent crash log is from Friday, June 22.

A screenshot of our server's mod folder is included.

This is my first time reporting an issue on GitHub -- kinda new to all of this -- so please let me know if you need anything else from me. We really like this mod and would love to support it!

![screen_shot_2018-06-26_at_10 46 36_pm](https://user-images.githubusercontent.com/40618503/41950249-d80260f4-798a-11e8-9eee-0b1a2c9dba7d.png)

**Comment by opencma** [comment]
I cannot determine the cause of the error without a crash report.

**Comment by Neonit** [comment]
I have this issue for a pickup not tossed by anyone. I broke a chest and the item dropped into my character. In that very moment my client gets kicked and the server displays an error.
```
net.minecraft.util.ReportedException: Adding item to inventory
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zin000(NetHandlerPlayServer.java:2047) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_25]
        at net.minecraft.entity.player.InventoryPlayer.getSpongeSlot(InventoryPlayer.java:1743) ~[aec.class:?]
        at net.minecraft.entity.player.InventoryPlayer.redirect$onAdd$zha000(InventoryPlayer.java:1762) ~[aec.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70452_e(InventoryPlayer.java:284) ~[aec.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_191971_c(InventoryPlayer.java:425) ~[aec.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70441_a(InventoryPlayer.java:378) ~[aec.class:?]
        at net.minecraft.entity.item.EntityItem.redirect$onAddItemStackToInventory$zfp000(EntityItem.java:778) ~[acl.class:?]
        at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:400) ~[acl.class:?]
        at net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$zgo000(EntityPlayer.java:3713) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
```

I don't know how to display the other 10 lines of the trace. The server continues running. But as my character was saved in the pickup, joining will kick my client again. I reset my save and walked into the pickup and got kicked again.

If I remove MultiHotbar Core from the server there are no problems with picking the item up.

**Comment by Neonit** [comment]
I opened a new issue for this, because I digged into my problem a bit and found out more. See here: https://github.com/rolandoislas/multi-hotbar/issues/56
